kind: api
apiVersion: api.webmethods.io/v1
metadata:
  name: jul101817
  namespace: dev
  version: 1.0
  tags:
    - swagger
    - jul9
    - sample
  type: REST
spec:
  api-spec: 
    $path: petstore.yaml
  policy-sequence: 
    - $ref: dev:dev_policies:1.0