#Conditional routing
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: default_route
  version: 1.3
  namespace: dev
spec:
  default-endpoint:
    $ref: dev:default_endpoint:1.1
  conditional-endpoints:
    - condition: |
        "(${request.headers.test} equals test1) or
        (${request.headers.test} notEquals ${request.payload.jsonPath[$.customer.name]})"
      endpoint:
        $ref: dev:default_endpoint:1.2

---
kind: Route
apiVersion: api.webmethods.io/beta
metadata:
  name: default_route
  version: 1.4
  namespace: dev
spec:
  loadbalance-endpoints:
    - $ref: dev:default_endpoint:1.3
      suspend-on-duration: 40s
    - $ref: dev:default_endpoint:1.2
      suspend-on-duration: 40s

